trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Job1
    steps:
    - bash: echo Build Stage - Job 1!
    - bash: echo ${Build.BuildNumber}
    - bash: echo ${Build.BuildId}
    - bash: echo ${Build.SourceBranchName}
    - bash: echo ${Build.SourcesDirectory}
    - bash: echo ${Build.ArtifactStagingDirectory}
    - bash: echo ${System.DefaultWorkingDirectory}
    - bash: ls -R ${System.DefaultWorkingDirectory}
  - job: Job2
    steps:
    - bash: echo Build Stage - Job 2!

- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: Job1
    steps:
    - bash: echo Dev Deploy Stage - Job 1!

- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: Job1
    steps:
    - bash: echo QA Deploy Stage - Job 1!

- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
  - job: Job1
    steps:
    - bash: echo Prod Deploy Stage - Job 1!