trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Job1
    steps:
    - bash: echo Build Stage - Job 1!
  - job: Job2
    steps:
    - bash: echo Build Stage - Job 2!

- stage: Dev-Deploy
  jobs:
  - job: Job1
    steps:
    - bash: echo Dev Deploy Stage - Job 1!

- stage: QA-Deploy
  jobs:
  - job: Job1
    steps:
    - bash: echo QA Deploy Stage - Job 1!

- stage: Prod-Deploy
  jobs:
  - job: Job1
    steps:
    - bash: echo Prod Deploy Stage - Job 1!
