trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Job1
    steps:
    - bash: echo Build Stage - Job 1!
  - job: Job2
    steps:
    - bash: echo Build Stage - Job 2!

- stage: DevDeploy
  jobs:
  - job: Job1
    steps:
    - bash: echo Dev Deploy Stage - Job 1!

- stage: QADeploy
  jobs:
  - job: Job1
    steps:
    - bash: echo QA Deploy Stage - Job 1!

- stage: ProdDeploy
  jobs:
  - job: Job1
    steps:
    - bash: echo Prod Deploy Stage - Job 1!
